version: '3.8'

services:
  endor_python_mongodb:
    image: mongo:latest
    container_name: endor_python_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - endor_python_mongodb_network

  endor_python_mongodb_dev:
    build:
      context: ../../../
      dockerfile: infrastructure/docker/development/app/Dockerfile
      args:
        - ENVIRONMENT=development
    container_name: endor_python_mongodb_dev
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "8005:8000"
    volumes:
      - ../../../app:/usr/endor_python/app:rw
    networks:
      - endor_python_mongodb_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      - endor_python_mongodb

networks:
  endor_python_mongodb_network:
    driver: bridge

volumes:
  mongodb_data:
